services:
  app:
    image: ghcr.io/sabnak/kbtracker:latest
    container_name: kbtracker_app
    environment:
      DATABASE_URL: postgresql://kbtracker:kbtracker@postgres:5432/kbtracker
      GAME_DATA_PATH: /data
      TZ: Europe/Moscow
    volumes:
      # Поменяйте пути! Часть после ":" остаётся неизменной.
      #
      # Путь к установленной игре. Если игр несколько, то каждый с новой строки!
      # Например: - 'C:/Games/Kings Bounty Darkside:/data/Darkside:ro'
      - '/path/to/your/game/Darkside:/data/Darkside:ro'
      #
      # Путь к сохранениям игр. Замените "C:/Users/<USERNAME>" на свой путь.
      - 'C:/Users/<USERNAME>/Documents/my games:/saves:ro'
    ports:
      - "9333:80"
    networks:
      - kbtracker-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: kbtracker_postgres
    environment:
      POSTGRES_USER: kbtracker
      POSTGRES_PASSWORD: kbtracker
      POSTGRES_DB: kbtracker
      TZ: Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - kbtracker-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kbtracker"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  kbtracker-network:
    driver: bridge

volumes:
  postgres_data:
